### PR TITLE
Add const to cmp_value parameters of vector synchronization apis

### PR DESCRIPTION
**Pull request by stewartl318**
# Summary of changes
Add const to *cmp_values in vector synchronization apis

# Proposal Checklist
- [x] Link to issue(s)
- [x] Changelog entry
- [x] Reviewed for changes to front matter
- [x] Reviewed for changes to back matter

### CODE REVIEW

**Comment by stewartl318** [comment]
Issue #542

**Comment by stewartl318** [comment]
PR should be rebased onto rc1

**Comment by davidozog** [comment]
Question from WG: add this as new function signature for v1.6 - or add as an errata for v1.5?

**Comment by jdinan** [comment]
This reference may be help with regard to C backwards compatibility: https://stackoverflow.com/questions/5083765/does-changing-fmystruct-a-to-fconst-mystruct-a-breaks-api-abi-in-c/5083976#5083976

As discussed, it may break tools that aren't updated with const as the call to the tool's binding for the function can potentially discard const from the argument passed by the application, which causes a compile time error.

A potentially bigger issue is with type-generic C++ bindings (which SOS has). The function name mangling will be different for the updated function and this will cause ABI breakage. Type-generic C++ bindings would need to add both const and non-const versions of the function. This isn't an issue in C because generic type selection simply chooses an ordinary C function name for one of the existing non-generic functions.

**Pull request merged**
