### PR TITLE
Make consistent description for nonblocking routines in fence/quiet routines.

### PR DESCRIPTION
**Pull request by min-si**

### CODE REVIEW

**Comment by min-si** [comment]
The second commit "Change AMOs to AMO in sync section" is simply a grammar issue, and is unrelated to the nonblocking routine description. Putting these commits dependently can avoid merge conflict (they change the same line). Please let me know if this is not OK for section review.

**Comment by spotluri** [comment]
@min-si that is fine by me. I am a planning to merge all the PRs into the section PR anyways, so that we have one for approvals.

**Comment by min-si** [comment]
Great. I think it might be easier for you to merge if we create future PRs against the section PR.

**Comment by min-si** [comment]
Close it as already merged into section/sync PR.

**Pull request closed without merging**
