### PR TITLE
Update example codes

### PR DESCRIPTION
**Pull request by jamesaross**
After reviewing and running all of the examples, I noticed there were several bugs with non-deterministic execution or incorrect reporting.  The examples were also inconsistent in formatting and style.  Some used barriers or extra code which were not required.  Others could be simplified and have explicit barriers removed.  Many used global variables and arrays when statically defined variables and arrays would be sufficient and simpler.  There are also codes that use `shmem_malloc()` and `shmem_free()` when a simple static variable or array declaration would work.  A couple codes were updated to use the C11 Generics.

I have incorporated James Dinan's earlier changes which passed the committee vote.

Below is a summary table.  All codes generally had minor formatting improvements and were updated with C99-style declaration and initialization.

file |bug fix|global to static w/ initialization|2 to 3 space indent|4 to 3 space indent|tab to 3 space indent|remove explicit barrier|malloc to static|simplify main()|C11 Generic|
|-|-|-|-|-|-|-|-|-|-|
| hello-openshmem.c| | |X| | | | |X| |
| shmem_add_example.c|X| | | | |X| | | |
| shmem_alltoall_example.c|X|X| |X| |X| | | |
| shmem_alltoalls_example.c|X|X| |X| |X| | | |
| shmem_barrier_example.c|X|X| | | | | | | |
| shmem_barrierall_example.c| |X| | | | | | | |
| shmem_broadcast_example.c| |X| | | |X| | | |
| shmem_collect_example.c|X|X| | | | | | | |
| shmem_cswap_example.c| | | | | | | | | |
| shmem_fadd_example.c| | | | | |X| | | |
| shmem_fence_example.c| |X|X| | | | | | |
| shmem_finalize_example.c| |X| | | | | | |X|
| shmem_finc_example.c| |X| | | | | | | |
| shmem_g_example.c| |X| | | | | | | |
| shmem_global_exit_example.c| | |X| | | | | | |
| shmem_inc_example.c|X| | | | |X| | | |
| shmem_iput_example.c| | | | | | | | | |
| shmem_lock_example.c| |X| | | | | |X|X|
| shmem_mype_example.c| | |X| | | | | | |
| shmem_npes_example.c| | |X| | | | | | |
| shmem_p_example.c| |X| | | |X|X| | |
| shmem_ptr_example.c| | | | | | | | | |
| shmem_put_example.c| | | | | | | | | |
| shmem_quiet_example.c| |X|X| | | | | | |
| shmem_swap_example.c| | | | | | |X| | |
| writing_shmem_example.c| | | | |X| | |X|X|

### CODE REVIEW

**Comment by jeffhammond** [comment]
The description indicates you are changing one and only one file.  Your PR changes 26 files.  Please reconcile these.

**Comment by jamesaross** [comment]
@jeffhammond 
Yes, three weeks ago it was just one file that I had noticed during the last vote.  And then I looked into the rest of them and realized there were quite a few issues.  So I took some time to update every one.

**Comment by jamesaross** [comment]
Could someone add the `PendingReading` label?

**Comment by jdinan** [comment]
*Feedback from Feb. 21 proposal reading*

Overall:

The captions may have become inconsistent in terms of referring to C/C11 generic.  Do any of the captions need to be updated to reflect the new changes?

Want to have a mixture of symmetric object declarations (globals, static, etc)

shmem_broadcast_example:
 - Does the barrier need to remain?
 - Will know after Manju's barrier proposal is discussed

shmem_collect_example:
 - Why was the lock introduced into this example?
 - Added to avoid printfs getting interleaved
 - Add comment to this example to describe why the lock was used

shmem_global_exit_example:
  - Add #include <stdio.h> for fopen()

shmem_iput_example:
  - In comment, replace "words" with "elements"

shmem_lock_example:
  - This is such a weird example ...

shmem_my_pe / npes_example:
  - Combine into a single example

shmem_p_example:
  - Use FLT_EPSILON from float.h and use M_E from math.h?
  - epsilon and e don't need to be static

shmem_put_example:
  - In comment, replace "words" with "elements"

shmem_quiet_example:
  - Would be nice to remove puts 3 and 4, but leave this to future work

**Comment by jamesaross** [comment]
@jdinan,

In the most recent commits, I did not modify the shmem_barrier_example, shmem_global_exit_example, or shmem_quiet_example.  The shmem_global_exit_example already had stdio.h, it just wasn't visible in the git diff.  The only significant code change was introduced in the shmem_lock_example, which was refactored to be more of a standard remote counter increment example rather than the weird sleep timing example.

I updated the example code captions where I had changed the example code from C to C11 generics.  I also changed the captions where they were missed from a prior pull request that updated the example codes to C11 generics.

**Pull request merged**
