### PR TITLE
Add \ENVVAR and \KEYWORD macros

### LINKED ISSUE #126: Environment Variables missing styling
Library constants --> `\CONST`
Library variables --> `\VAR`
Environment variables?

Only existing actual use is for `SHMEM_SYMMETRIC_SIZE`, which does not *feel* correct.
We probably need a new macro.
```bash
$ grep 'SHMEM\\_SYMMETRIC\\_SIZE' * -R
content/environment_variables.tex:\texttt{SHMEM\_SYMMETRIC\_SIZE} & non-negative integer & number of bytes to
content/shmem_malloc.tex:    adjust the size of the heap using the \CONST{SHMEM\_SYMMETRIC\_SIZE} environment
content/shpalloc.tex:    adjust the size of the heap using the \CONST{SHMEM\_SYMMETRIC\_SIZE} environment
```

Affects deprecated `SMA_*` environment variables in Annex F.

### PR DESCRIPTION
**Pull request by jdinan**
Closes #126

### CODE REVIEW

**Comment by nspark** [comment]
👍

**Comment by jdinan** [comment]
Need +1 from another committee member to merge this as a document edit.

**Comment by BryantLam** [comment]
:+1:

**Comment by jdinan** [comment]
Merging as document edit.

**Pull request merged**
