### PR TITLE
Text Edits in Front Matter - PEs may be Multithreaded 

### PR DESCRIPTION
**Pull request by manjugv**

### CODE REVIEW

**Comment by RaymondMichael** [comment]
This was merged into RaymondMichael, so I'll pull it off the queue

**Comment by jdinan** [comment]
@manjugv If this has been merged elsewhere, could you please close the PR?

**Comment by jdinan** [comment]
@manjugv Ping ...

**Comment by manjugv** [comment]
Thanks @jdinan This PR should be closed.

**Pull request closed without merging**
