### PR TITLE
Clarified header files for standardized OpenSHMEM API

### PR DESCRIPTION
**Pull request by BryantLam**
The only locations where `shmem.h` and `shmem.fh` are spelled out are in example codes and Annex A. Added clarification to Section 5: Language Bindings.

### CODE REVIEW

**Comment by jdinan** [comment]
What do you think about adding the ```mpp/*``` location for the header files to the deprecation annex?  There's lots of code out there that expects the headers to be in this subdirectory off the include search path.

**Comment by swpoole** [comment]
Any major negative impacts we know of?

**Comment by jdinan** [comment]
The ```mpp/``` copies of the header are required for backward compatibility in OpenSHMEM 1.0, but they disappear after that.  I think adding them to the deprecation chapter would be a positive change in terms of re-capturing these as a backward compatibility feature that may be removed in the future.

**Comment by shamisp** [comment]
Concerns about backward compatibility ?

**Comment by BryantLam** [comment]
Discussion related to #49.

I don't believe there are any concerns with backwards compatibility.  I'll work on a separate ticket later today to add the `mpp/*` headers into the deprecation table with a still-supported flag. This location can be formally removed at a later date (possibly alongside the official removal of Fortran).

**Comment by swpoole** [comment]
+1

Best,
Steve (ADTSC)

**Comment by jdinan** [comment]
As long as you're fixing this, could you also add a ```\header``` command to ```utils/defs.tex``` and update the formatting of the other references to ```shmem.h``` and ```shmem.fh``` in Annex A, 8.1.9, and 8.1.10 to use the new command?

**Comment by jdinan** [comment]
@BryantLam I don't think that this requires a changelog entry, since there is no user-visible change.  In fact, if you drop the changelog entry, I would be inclined to handle this as a document edit.

**Comment by jdinan** [comment]
@BryantLam Would you like to bring this forward for voting at the next meeting?  It looks like the only change needed is to remove the changelog entry.

**Comment by BryantLam** [comment]
@jdinan Removed changelog entry. Converting this PR to a DocEdit as you suggested. Feel free to merge when reviewed/ready.

**Comment by jdinan** [comment]
Looks good to me.  I'm fine with processing this as a document edit.  Can I get a +1 from another committee member?

**Comment by swpoole** [comment]
+1

Best,
Steve (ADTSC)

**Pull request merged**
