### PR TITLE
Semantics clarification for visibility ordering guarantees.

### PR DESCRIPTION
**Pull request by shamisp**
Redmine issue http://www.openshmem.org/redmine/issues/169

### CODE REVIEW

**Comment by shamisp** [comment]
List of changes in this PR in respect to the version that was presented at OpenSHMEM workshop http://www.openshmem.org/redmine/issues/169 (see the attached file ordering_proposal_v2.pdf).

1. Added change log entry to the "Changes to this Document" chapter
2. Added sentence ```The shmem_barrier routine can be used to portably ensure that memory access operations observe remote updates in the order enforced by initiator PEs. ``` to shmem_barrier.
3. Added sentence ```The shmem_barrier_all routine can be used to portably ensure that memory access operations observe remote updates in the order enforced by initiator PEs.``` to shmem_barrier_all
4. ```at the target PE``` was changed ```by the target PE```
5. Clarification in shmem_fence. The statement was moved to the second sentence in the paragraph. Added clarification statement: ```shmem_wait, shmem_wait_until,
 shmem_barrier, shmem_barrier_all routines can be called by the target PE to guarantee  ordering of its memory accesses.```
6. Clarification in shmem_quiet. The statement was moved to the last sentence in the paragraph.  Added clarification statement: ``` shmem_wait, shmem_wait_until,
 shmem_barrier, shmem_barrier_all routines can be called by the target PE to guarantee  ordering of its memory accesses.```

**Comment by jdinan** [comment]
@shamisp Please remove color macros / reviewing markup.  :)

**Comment by shamisp** [comment]
@jdinan I removed color macros

**Comment by jdinan** [comment]
Thanks!  @dkhaldi This looks ready to merge.

**Pull request merged**
