### PR TITLE
Create initial readme.md

### PR DESCRIPTION
**Pull request by jdinan**

### CODE REVIEW

**Comment by jdinan** [comment]
@abouteiller, please let us know if there's anything else that should be included here.

**Comment by jdinan** [comment]
It's safe to ignore Travis.  There's no .travis.yml on ```master```, it's only on the ```osh_spec_next``` branch.

**Comment by abouteiller** [comment]
That's a good start. 👍 

Maybe we can add how we manage labels, milestones and mark text as reviewed.

**Comment by jdinan** [comment]
I think how/where we manage issues (github vs redmine) and milestones will require more discussion.  I suggest that we merge this basic info for now and continue adding to it.  We could also use the wiki for the more detailed instructions, versus putting it in the README.

**Comment by abouteiller** [comment]
Agreed.

**Comment by swpoole** [comment]
+1 on the discussion option. I will try and get the logistics going for next week.

Best wishes
Steve...

**Comment by jdinan** [comment]
@abouteiller, I added a blurb about referencing the Redmine ticket for full proposals.
@dkhaldi, could you provide the second review and merge if this looks good?  Thanks!

**Comment by dkhaldi** [comment]
@jdinan How do you suggest the pull request to reference the Redmine ticket being used to track the proposal? in the name of the PR branch or where? I am not clear on this.
Also, why travis shows to me that checks have failed?

**Comment by jdinan** [comment]
@dkhaldi Travis is failing because the ```.travis.yml``` script is only on ```osh_spec_next``` and not on ```master```.  It is safe to ignore this; Travis is just complaining that it can't test the branch.  With regard to how to reference the Redmine ticket, I prefer to get more experience with the process and then document what works, rather than mandating a particular process.

**Comment by dkhaldi** [comment]
Sounds good to me.

**Pull request merged**
