### PR TITLE
Simplify and update the makefile

### PR DESCRIPTION
**Pull request by jdinan**
The existing makefile doesn't run pdflatex enough times:

    LaTeX Warning: Label(s) may have changed. Rerun to get
    cross-references right.

Update the makefile to fix the above (run standard 3 times), improve
build dependencies, and remove bit rotted DVI/PS build.

Signed-off-by: James Dinan <james.dinan@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
Ready for review.

**Comment by BryantLam** [comment]
Have you considered using `latexmk`? I typically use that to "run pdflatex enough times."

**Comment by jdinan** [comment]
Latexmk is great.  I wasn't sure if others who build the spec would have it installed, but also we pass ```-halt-on-error``` directly to pdflatex in Travis CI testing and I'm not sure whether we can get the same error behavior from ```latexmk```.

**Comment by jdinan** [comment]
@manjugv ORNL touched the Makefile last.  What do you think of these changes?

**Comment by manjugv** [comment]
@jdinan 👍

**Pull request merged**
