### PR TITLE
fix apidefinition environment

### PR DESCRIPTION
**Pull request by boehms**
At the last f2f the API Notes none was brought up. I looked at how they can be removed. This should fix the apidescription environment and the usage of apidesctable.
Additionally the empty API Notes are removed.

### CODE REVIEW

**Comment by manjugv** [comment]
This could be handled as document edit ? @jdinan @nspark What do you think ?

**Comment by jdinan** [comment]
This seems reasonable to handle as a document edit.  I'll be back in the office next week and can do a detailed review then.  In the meantime, +2 from other committee members would be helpful.

**Comment by swpoole** [comment]
+1

**Comment by nspark** [comment]
@boehms You missed the removal of "Notes: None" in:
* `shmem_calloc`
* `shmem_atomic_{fetch_and, and, fetch_or, or, fetch_xor, xor}`
* `shmem_test`

Interestingly, I think these are all interfaces that I added.

**Comment by boehms** [comment]
Those might have come in with the merge. I will fix them.

**Comment by nspark** [comment]
:+1:

**Comment by jdinan** [comment]
I'm seeing an indentation problem in the API description table, e.g. for SHMEM_ATOMIC_SWAP.  There's also a bad break that splits the table header and rows for SHMEM_ATOMIC_FETCH_INC.

[main_spec.pdf](https://github.com/openshmem-org/specification/files/1191882/main_spec.pdf)

**Comment by boehms** [comment]
Making sure we don't have a page break in the table will need some reworking of the environments and the commands. It can be done, but will require some more work.

**Comment by jdinan** [comment]
The internet suggests numerous ways to do this.  The simplest is to wrap it in a table float, which is unbreakable (with "here" placement).  Alternatively, there are solutions like this one: https://tex.stackexchange.com/questions/94699/absolutely-definitely-preventing-page-break

**Comment by boehms** [comment]
The problem is, that is is not actually one table. Each \apitablerow is its own tabular. And to make things harder, they are in a quote environment (\apidesctable). If we where to use a float, it would break out of the quote environment.

**Comment by manjugv** [comment]
@boehms @jdinan do you have an agreement here ?

**Comment by jdinan** [comment]
Well ... now we have other formatting weirdness.  Is there some flexible vspace we can put in front of the table to fix this?

screen shot 2017-08-27 at 10 07 29 pm

**Comment by boehms** [comment]
Are you referring to the sentence on the bottom on page 33?

I am not aware of a flexible vspace. I think the formatting is something we should take care of, when the content of the document is close to being finalized. The table might move with new content.

**Comment by jdinan** [comment]
Could you take a look at \longtable (ref #123)?  That seems like it could provide a good solution.

**Comment by jdinan** [comment]
Also, FWIW, if you separate the API table changes, we can merge the rest of this PR while we sort out the table formatting.

**Comment by boehms** [comment]
@jdinan How about this?

**Comment by nspark** [comment]
Replaced by #330 (though it doesn't address table and whitespace changes)

**Pull request closed without merging**
