### PR TITLE
Extension #202: Improved Annex F for Deprecated API

### PR DESCRIPTION
**Pull request by BryantLam**
Redmine: http://openshmem.org/redmine/issues/202

The base commit for this pull request is essentially unchanged from #202 annexF_revision_proposal2.pdf (07/13/2016 01:11 PM) from the Redmine. Changes atop this base commit reflect feedback from the OpenSHMEM Workshop 2016 and misc additions.
- WORKSHOP: Simplified rationale text for **SHMEM_CACHE**
- NEW: Changed rationale text for **_SHMEM_\* constants**
- NEW: Table includes language specifiers for previously deprecated functions
- NEW: Changelog text (Where did v1.4 go?)
- Misc formatting

TODO: Table could still use some formatting wizardry. That's for another day.

### CODE REVIEW

**Comment by jdinan** [comment]
Draft for 10/20/2016 meeting: [main_spec.pdf](https://github.com/openshmem-org/specification/files/542797/main_spec.pdf)

**Comment by jdinan** [comment]
This ticket was ratified 12/15/16.  @BryantLam could you please push a patch that removes the color macros and removes all of the deleted text?  Thanks!

**Comment by BryantLam** [comment]
Merge conflict with #14 (both texts are ratified). I am going to leave the Annex-F entry for the `SMA_` variables. The deprecation rationale will have to come in a separate PR as noted in #14.

**Comment by BryantLam** [comment]
Ready for merge.

**Comment by jdinan** [comment]
@dkhaldi looks good to me.  Merge when ready.

**Comment by BryantLam** [comment]
Related to #33.
These changes do not note that Fortran routines MY_PES and NUM_PES are deprecated.

**Comment by jdinan** [comment]
We intend to deprecate all of the Fortran interfaces, so I think we can just put them back and blanket deprecate.  In any case, even if they were deprecated, they should not have been removed from the spec.

**Pull request merged**
