### PR TITLE
DOC-edit: RM unnecessary white spaces in backmatter and defs

### PR DESCRIPTION
**Pull request by naveen-rn**
Removing unnecessary white spaces in the backmatter and def files.

### CODE REVIEW

**Comment by naveen-rn** [comment]
Also, there is an undefined reference to MPI section from the version:1.1 - changes to document section. That needs some fix - I have left it as it is for now. Looks like an side-effect of removing MPI section in version:1.5

**Comment by jdinan** [comment]
Can we please get review/approval from another committee member to merge this as a document edit?

**Comment by manjugv** [comment]
Looks fine .. 👍

**Comment by jdinan** [comment]
Thanks @naveen-rn for the doc edit and @manjugv for the review!

**Comment by jdinan** [comment]
@naveen-rn This doesn't seem to have shortened the diff displayed for #244 and #218.  Not sure if merging master into those branches will help.  🤷‍♂️

**Comment by naveen-rn** [comment]
> This doesn't seem to have shortened the diff displayed for #244 and #218. Not sure if merging master into those branches will help.

Changes are reflected after rebasing with master.

**Pull request merged**
