### PR TITLE
redo PR 17

### PR DESCRIPTION
**Pull request by jeffhammond**
This is the correct version of https://github.com/openshmem-org/specification/pull/17

### CODE REVIEW

**Comment by jdinan** [comment]
I'd like to see a changelog entry noting that the complex routines are no longer defined for the "generic" C API.  This is technically backward compatibility breakage, although I do not expect any users to be impacted.  There should also be a changelog entry noting that C++ bindings are added for these routines.

**Comment by jeffhammond** [comment]
> I'd like to see a changelog entry
> 
Sure, whenever the changes are finalized. 
> noting that the complex routines are no longer defined for the "generic" C API. This is technically backward compatibility breakage, although I do not expect any users to be impacted.
> 
Why can't they be supported under generic C API? C99 is compatible with C11. 

You want me to change to C99+ instead?
> There should also be a changelog entry noting that C++ bindings are added for these routines.
> 
Sure.

**Comment by jdinan** [comment]
Changelog entries are easy to write and will help a reader understand the intent of your proposal.

The "generic" C API also encompasses earlier versions of C (since we don't specify) that don't have the _Complex type.  If someone is using a C89 compiler, they no longer get the complex functions.

**Comment by jeffhammond** [comment]
By "generic" C API, you apparently do not mean the `_Generic` C API, as I originally thought.

As the generic C API could not have worked with a C89 compiler without depending on the existence of a user-defined type ` complex` whose definition is not specified anywhere in the standard, I don't see any reason to identify breakage.

If you can give me a specific example of something ISO-compliant that would be broken by this, I'll revise my position.

**Comment by nspark** [comment]
By "generic C API" do you mean C11 `_Generic` or the "vanilla" C API? There isn't any support for complex types in the C11-generic API (for put/p/iput/get/g/iget) and I hadn't planned on adding them in the "expanded RMA types" PR #13.

**Comment by jdinan** [comment]
These functions *must have worked* and *may still work* in a non-C99 compiler in some SHMEM implementation.  Your proposal will remove that functionality.  Whether you find is aesthetically appealing or not, we must note the breakage of backward compatibility in the changelog entry.

**Comment by jdinan** [comment]
@nspark s/generic/vanilla/

**Comment by jeffhammond** [comment]
> These functions must have worked and may still work in a non-C99 compiler in some SHMEM implementation.
> 
Worked in what sense? The type in the signature is defined nowhere in the spec.

Breaking undefined features seems unworthy of documentation. 
> Your proposal will remove that functionality. Whether you find is aesthetically appealing or not, we must note the breakage of backward compatibility in the changelog entry.
> 
I'll note that implementation-defined behavior is still implementation-defined.

I refuse to acknowledge "complex" has a meaning in C89 and I refuse to build standards documents on non-standard compiler extensions.

**Comment by jdinan** [comment]
@jeffhammond - just because we didn't define it fully in OpenSHMEM doesn't mean that it wasn't fully defined and functional in an earlier SHMEM implementation.

**Comment by jeffhammond** [comment]
And implementers are permitted to carry that torch. The standard should not.

**Comment by jdinan** [comment]
I agree and I support the change.  However, it breaks backward compatibility (albeit, for a feature that was ill-defined) and this should be noted in the changelog.

**Comment by jdinan** [comment]
@jeffhammond Is this superseded by #29?

**Comment by jeffhammond** [comment]
@jdinan Yeah, @nspark should feel free to pull in anything he likes about this ticket.

**Pull request closed without merging**
