### PR TITLE
Add SHMEM_SYNC_SIZE constant

### PR DESCRIPTION
**Pull request by jdinan**
This proposal was ratified at the August meeting and is ready to be merged.

### CODE REVIEW

**Comment by jdinan** [comment]
@dkhaldi, please review and merge when ready.  Thanks!

**Comment by shamisp** [comment]
IMHO, we need more than one review for any PR.

**Comment by jdinan** [comment]
This is why we ask for a PR before voting.  :)

Travis should also be up and running now.  Although, it doesn't seem to want to pick up these existing PRs.

**Comment by shamisp** [comment]
Also, the author need to include some reference to redmine ticket that actually states that the changes was voted in.

**Comment by jdinan** [comment]
Ref: http://www.openshmem.org/redmine/issues/205

**Comment by jdinan** [comment]
Shoot, I forgot to include a ref to the library constants section in the changelog entry.  On the plus side, adding the commit convinced Travis to run on this PR.

**Comment by dkhaldi** [comment]
Jim,
The changelog new section you introduced is entitled "Version 1.4" however, the cover page of the spec says that this is Version 1.5. I understand we did not discuss the next release name and it is early to do this anyway. But I would like to be consistent in the document. Shall I go ahead and change 1.5 to 1.4 in the cover page. 

Please let me know your thoughts.

**Comment by jdinan** [comment]
I can update this to 1.5; that would be easier.  Most people seem to want 1.5 as the next version number.

**Comment by dkhaldi** [comment]
Also, in "Refer to the individual collective operations for more information about the usage of
this constant.", do you want to add a hyperlink to "collective operations" in the spec; this is what other entries in the table do (again, just to be consistent :))?

**Comment by jdinan** [comment]
Updated.  Note that I also updated "collective operations" to "collective routines" to match the name of the section that was being referenced.

**Comment by dkhaldi** [comment]
Thank you.

**Comment by swpoole** [comment]
How does this actually sync up with some of the changes we had planned
for V1.4 and V1.5?

Steve...

On 8/15/16 19:23, Dounia Khaldi wrote:
> Jim,
> The changelog new section you introduced is entitled "Version 1.4" however, the cover page of the spec says that this is Version 1.5. I understand we did not discuss the next release name and it is early to do this anyway. But I would like to be consistent in the document. Shall I go ahead and change 1.5 to 1.4 in the cover page. 
>
> Please let me know your thoughts.
>
>

-- 
Regards,
Steve...

"Don't mistake my kindness for weakness. I am kind to everyone,
but when someone is unkind to me, weak is not what you are going
to remember about me." -- Al Capone.

**Comment by swpoole** [comment]
If we add a hyperlink, how will that help in a printed copy?

Steve...

On 8/15/16 19:30, Dounia Khaldi wrote:
> Also, in "Refer to the individual collective operations for more information about the usage of
> this constant.", do you want to add a hyperlink to "collective operations" in the spec; this is what other entries in the table do (again, just to be consistent :))?
>

-- 
Regards,
Steve...

"Don't mistake my kindness for weakness. I am kind to everyone,
but when someone is unkind to me, weak is not what you are going
to remember about me." -- Al Capone.

**Comment by jdinan** [comment]
@swpoole, as long as we're consistent with the draft version number, it should be easy for us to find and update to whatever the committee chooses for the final draft.  In the future, there might be less chance of error to use "X.Y" or "1.NEXT".

With regard to the printed copy, we don't generate the section number currently, but all the info is there in the macro, so it should be possible.  If you're interested in that change, I think it might be best to treat it as a proposal to update the formatting.

**Comment by swpoole** [comment]
Agreed. Many folks do not have easy access to the soft copy of the spec.

Steve...

On 8/15/16 20:23, James Dinan wrote:
> @swpoole, as long as we're consistent with the draft version number, it should be easy for us to find and update to whatever the committee chooses for the final draft.  In the future, there might be less chance of error to use "X.Y" or "1.NEXT".
>
> With regard to the printed copy, we don't generate the section number currently, but all the info is there in the macro, so it should be possible.  If you're interested in that change, I think it might be best to treat it as a proposal to update the formatting.
>

-- 
Regards,
Steve...

"Don't mistake my kindness for weakness. I am kind to everyone,
but when someone is unkind to me, weak is not what you are going
to remember about me." -- Al Capone.

**Comment by nspark** [comment]
@jdinan Why did you list the `SHMEM_SYNC_SIZE` constant for C/C++ and Fortran separately (unlike the rest of the constants)?

**Comment by jdinan** [comment]
Eek, this is a typo..  But, I think this is within the powers of the document editor to fix, since it's an obvious typo with no impact on semantics.

Fix in #28.

**Pull request merged**
