### PR TITLE
Update example formatting

### LINKED ISSUE #397: Make examples easier to read
IMO, the examples are not so easy to read with the current choice of color stylings. Ideas to make it easier?

- Change the background color to 80% or 90% white instead of the current ~50% white.
- ...

### PR DESCRIPTION
**Pull request by nspark**
- Remove background color
- Add frame to examples

Closes #397

### CODE REVIEW

**Comment by BryantLam** [comment]
Would it be worthwhile to make the green and blue coloring darker and/or bolder? The text is readable as is, but it would stand out more if the coloring was more pronounced like in the purple for `TYPENAME` and `TYPE`.

**Comment by nspark** [comment]
Here's an example for which the colors were made darker.

Old:
ColorsOld

New:
ColorsNew

**Comment by BryantLam** [comment]
Looks great!

**Comment by jamesaross** [comment]
Since this is more of an aesthetics thing, it should probably be discussed at the next meeting.  I prefer the grey background, although lighter than in rc1 (like 97%) and a grey border rather than black.  The github color scheme is about right to me.  The border is necessary to identify code examples that cross page breaks. I also prefer that the API blocks be the lighter grey, but without a border in order to distinguish them from the code examples.

**Comment by nspark** [comment]
@manjugv Could we have some time near the end of Friday's RCM to discuss this?

**Comment by manjugv** [comment]
> @manjugv Could we have some time near the end of Friday's RCM to discuss this?

👍 I have added this to the [agenda](https://github.com/openshmem-org/specification/wiki/March-20th#miscellaneous).

**Comment by jdinan** [comment]
Replaced by https://github.com/jdinan/specification/pull/16

**Pull request closed without merging**
