### PR TITLE
Add SHMEM_SYNC_SIZE constant

### PR DESCRIPTION
**Pull request by jdinan**
Ref: Redmine #205 (http://www.openshmem.org/redmine/issues/205)

### CODE REVIEW

**Comment by jdinan** [comment]
Please re-open.  This should not be closed until the merge is completed.

**Comment by dkhaldi** [comment]
Jim,
I think this happened after the deletion of the branches which I did few minutes ago. I just restored the branches since apparently, there are pull requests that are still related to them which I don't understand since the branches are supposed to be released. No development or PR should be attached to 1.3, right?

**Comment by jdinan** [comment]
That's right, PRs should be against ```osh_spec_next```.  I'll fix the PR on my end.  Forgot that I had PRs pending on the branches that are being deleted.  :)

**Comment by abouteiller** [comment]
I think we should have a summary document for git processes. I am in the process of moving my branches as well and was wondering against what I should rebase before I found this comment.

**Comment by dkhaldi** [comment]
Hi Aurelien,
I sent this email few days ago to the OpenSHMEM list: [OpenSHMEM-list] OpenSHMEM spec: new development branch.
I am copying it here in case you missed it:

"The master branch of the public repo of the spec (https://github.com/openshmem-org/specification) is now in sync with the released 1.3 specification. 

Please note that once your Redmine ticket is voted on successfully, the PR to merge the changes should be generated against the new development branch osh_spec_next that is also available in the public repo."

**Pull request closed without merging**
