### PR TITLE
Relaxed definition of SHMEM_MAX_NAME_LEN

### PR DESCRIPTION
**Pull request by BryantLam**
`SHMEM_MAX_NAME_LEN` now represents the maximum string length instead of the actual string length. The original definition has ambiguous implications with whether null/blank characters at the end of the relevant characters were counted or not.

Potentially a DocEdit, but this change technically relaxes the existing semantics even if the original semantics were sometimes not used in practice.

### CODE REVIEW

**Comment by jdinan** [comment]
I suggest we assign this to the front matter section committee.  If they are unanimous, we can merge it without going through the proposal process (it gets voted on later with all other such section edits).  If we go that route, there should be no need for a changelog entry.

Michael Raymond is the chair of the front matter section committee.  Other committee members: Swaroop, Nick, Tony Curtis, and Bryant.

**Comment by H2-He-O2** [comment]
This looks fine to me.

**Comment by jdinan** [comment]
Reading this again, I think this does merit a changelog entry.  Given that it's ready to read, I suggest we just follow the full proposal process.

**Comment by tonycurtis** [comment]
Looks ok.

**Comment by dkhaldi** [comment]
The definition of SHMEM_INFO_GET_NAME  (see 8.1.10) explains that null/blank characters at the end of the relevant characters are counted. 

In case you want to increase the scope of this ticket, I think the definition of SHMEM_VENDOR_STRING should appear before SHMEM_MAX_NAME_LEN in Section 6. Also, SHMEM_VENDOR_STRING appear only once in the spec: The spec does not explicitly say that SHMEM_INFO_GET_NAME returns 
 SHMEM_VENDOR_STRING

**Comment by BryantLam** [comment]
> The definition of SHMEM_INFO_GET_NAME (see 8.1.10) explains that null/blank characters at the end of the relevant characters are counted.

Very true. That definition conflicts with the current definition for `SHMEM_MAX_NAME_LEN` (exact length). This proposed change is attempting to adopt the more relaxed definition as seen in `shmem_info_get_name`.

> In case you want to increase the scope of this ticket, I think the definition of SHMEM_VENDOR_STRING should appear before SHMEM_MAX_NAME_LEN in Section 6.

I like this idea. I'll DocEdit this change in a separate PR.

> Also, SHMEM_VENDOR_STRING appear only once in the spec: The spec does not explicitly say that SHMEM_INFO_GET_NAME returns SHMEM_VENDOR_STRING

It does now! 😀 See ratified #51.

**Comment by dkhaldi** [comment]
:thumbsup:

**Comment by jdinan** [comment]
Thanks for merging the upstream changes.

**Pull request merged**
