### PR TITLE
Index for the spec.

### PR DESCRIPTION
**Pull request by j-mike-culhane**
This PR contains a rough draft for a potential index. This PR is meant to serve as a point of reference regarding how an index would appear in the spec. Please view and comment on whichever PR you think works better.

Note: I would like to stress that the 'Index for the spec' and 'Glossary for the spec' PRs are meant to serve as points of reference and, as they are currently, would require further editing before being added to the spec.

### CODE REVIEW

**Comment by jdinan** [comment]
I don't think this is an either/or choice.  The spec should have an index and there are tools for LaTeX to automatically generate it (e.g., https://en.wikibooks.org/wiki/LaTeX/Indexing).  We should be able to integrate such a change as a document edit.  The glossary (which also looks good) is new text and would require voting.

**Comment by jdinan** [comment]
@j-mike-culhane What's the status of this PR?  If possible, I'd like to consider including this in 1.4 as a document edit.

**Comment by jdinan** [comment]
Draft of current PR: [main_spec.pdf](https://github.com/openshmem-org/specification/files/1415390/main_spec.pdf)

**Comment by BryantLam** [comment]
I like the idea of an index but the current PR does need further work (it's a good first step!). There are trivial jumps mostly all to page 2 where the routines are introduced, but it's missing jumps to the relevant sections for each of those routines (e.g., reduction). Quickly scanning, there's also at least one arguably wrong jump: `Fence` jumps to page 85 (the start of p2p sync) but should either jump to the actual SHMEM_FENCE routine or have it be added.

**Comment by j-mike-culhane** [comment]
@jdinan @BryantLam 
I made some further changes and additions so that the index would be more thorough. Let me know what you guys think.

Picture: screen shot 2017-10-26 at 3 47 23 pm

**Comment by jdinan** [comment]
@j-mike-culhane I think this may be going a bit further than what is doable as a document edit.  Some of the new terms may be better indexed through the existing table of contents, rather than through an index.

To do this as a document edit to 1.4, I think we will have to stick to items that indisputably belong in an index: (1) constants, (2) environment variables, and (3) API routines.

Could you preserve this PR and create a second one that includes just these items?  Thanks!

**Comment by BryantLam** [comment]
I would like to be a final reviewer because backmatter will own this change after it's accepted. I'm weary of the `\index` insertion throughout the entire document and wonder if there's a better way.

**Comment by jdinan** [comment]
@BryantLam Glad to have your help.

**Comment by BryantLam** [comment]
I'm working on recreating an index rebased on OpenSHMEM 1.4rc3 because non-trivial changes to osh_spec_next will encounter a ton of merge conflicts when rc3 is merged in.

This branch is what I have so far:
https://github.com/jdinan/specification/compare/drafts/osh-1.4-rc3...BryantLam:osh-1.4-rc3/index

It looks intimidating, but it's actually easier to follow if you go through each commit in the history.

[Current preview of the index.](https://github.com/BryantLam/openshmem-specification/commit/453dab672a7d1582255eabdab21a3a45000a5b56#commitcomment-25348261)

Open issues and questions:
- Need to figure out how to column-break an index heading.
- Do we want to index the Fortran functions?

**Comment by BryantLam** [comment]
[Preview 2 is available](https://github.com/BryantLam/openshmem-specification/commit/3136b13f961bbb02b9d8e978e7419916c1ef47b3#commitcomment-25372739). This commit reflects a somewhat significant change to `Csynopsis`, etc. in order to support indexing of routines: it's a mixture of LaTeX and verbatim text.

The actual has some weird behavior with angle brackets. Still need to work that out.

**Comment by BryantLam** [comment]
[Preview 3](https://github.com/BryantLam/openshmem-specification/commit/7121852a3943019d2a8156a4991986a5d76e37d9#commitcomment-25576316). Final product. I doubt I'll make any structural changes at this point.

**Comment by nspark** [comment]
> [Preview 3](https://github.com/BryantLam/openshmem-specification/commit/7121852a3943019d2a8156a4991986a5d76e37d9#commitcomment-25576316). Final product. I doubt I'll make any structural changes at this point. Separate PR pending.

This is just my $0.02, but I think I have philosophical differences with the nature of this index. The index starts with a high-level topical structure, which means that if I'm looking up `SHMEM_FOO` (or `shmem_foo`) in the index, I _already have to know_ whether it's a constant, handle, or routine (including whether it's a C11, C/C++, or Fortran routine). If I already know that, I can just as easily look at the table of contents.

For now, only a few of these entries appear with more than one reference in the index, so I'm not sure how extensively the specification will cross-reference itself and allow the index to show its value.

**Comment by BryantLam** [comment]
You're not hurting my feelings. 😉  I added the categorization because it was easier for me to scan through the index, but I'm already familiar with the API and your rationale is completely justified. It should be a few macro changes to elide the categorization if that's what folks prefer (others, feel free to chime in!).

**Comment by BryantLam** [comment]
[Preview 4](https://github.com/BryantLam/openshmem-specification/commit/1f5f49454f6624ebbcfb3cde3e5edd657953c9c8). Reduced categorization.

**Comment by BryantLam** [comment]
Merged into OpenSHMEM 1.4 rc5 (https://github.com/BryantLam/openshmem-specification/commit/201b797138dc2ede9e2a3f83158c9cbe8af0166d). Closing.

**Pull request closed without merging**
