### PR TITLE
Clarify behavior of shmem_sync, shmem_broadcast, shmem_reduction, shmem_alltoall(s), shmem_collect when passed invalid team

### PR DESCRIPTION
**Pull request by agrippa**
Addresses issue openshmem-org#346

### CODE REVIEW

**Comment by agrippa** [comment]
@nspark @davidozog @jdinan @minsii please review

**Comment by nspark** [comment]
@agrippa Can you resubmit this PR against https://github.com/nspark/specification/tree/section/collectives?

**Comment by agrippa** [comment]
@nspark whoops, looks like I got confused by github's UI last night. Opening a different PR now.

**Comment by jdinan** [comment]
Moved to: https://github.com/nspark/specification/pull/12

**Pull request closed without merging**
