### PR TITLE
Add SVG format figures; fix usage of deprecated constants in wait

### PR DESCRIPTION
**Pull request by manjugv**

### CODE REVIEW

**Comment by jdinan** [comment]
Can we handle this as a section change, or would it be best to merge to openshmem-org:master?

**Comment by manjugv** [comment]
Ping @naveen-rn What is your preference as section chair for this issue ?

**Comment by naveen-rn** [comment]
I'm fine with this going into the section edit. close this PR and open one against naveen-rn/openshmem-1.5 branch in https://github.com/naveen-rn/specification/tree/naveen-rn/openshmem-1.5

**Comment by naveen-rn** [comment]
@manjugv Thanks for the fix.

**Comment by manjugv** [comment]
@naveen-rn Moved the branch as you have requested.

**Pull request closed without merging**
