### PR TITLE
RMA, AMO, Reduction edits

### PR DESCRIPTION
**Pull request by shamisp**
* Adding macro for subsubsubsection
* Moving blocking and non_blocking RMA into one subsubsection
* Moving blocking and non_blocking AMO into one subsubsection
* Updating AMO introduction to reflect support for non_blocking
operations
* Reduction paragraph was replaced with subsubsubsection to make the
text consistent

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
Fixing #216

**Comment by shamisp** [comment]
@nspark this PR touched collectives. Reduction used paragraphs and I made it consistent across chapters. Please let me know if this is okay. Otherwise I can open separate PR just with the reduction change.

**Comment by shamisp** [comment]
@manjugv can you please review as well. thanks

**Comment by jdinan** [comment]
Please move this PR to the relevant section committee branch.

**Comment by shamisp** [comment]
@jdinan How do I do it and what is the relevant branch ? thanks !

**Comment by jdinan** [comment]
You're the chair, so please create a branch on the current openshmem-org:master head for RMA/AMO/Signal section edits on your fork: shamisp:sec/rma-amo. Post the changes on this PR as a PR against that section committee branch, request reviews from your committee members, and merge into section edits once section committee approves. Thanks!

**Comment by shamisp** [comment]
@jdinan - got it. thanks.

**Comment by shamisp** [comment]
As @jdinan requested moved the PR here https://github.com/shamisp/specification/pull/1

I guess I have to ask @jdinan @nspark @manjugv re-approve the new PR. I will close this one and just reference the discussion from the new PR.

**Comment by jdinan** [comment]
@shamisp IIUC, this PR was superseded by https://github.com/shamisp/specification/pull/1. Can it be closed?

**Pull request merged**
