### PR TITLE
Teams Proposal

### PR DESCRIPTION
**Pull request by jdinan**
This is the teams proposal that was ratified on Sept. 26.  It has been moved to the openshmem-org repository to allow committee members to post PRs for section committee edits while we work on merging.

To do list:
 - [x] Remove change markers (@gmegan)
 - [x] Resolve merge conflicts (@jdinan)
 - [ ] Add changelog entry (moved to #301)
 - [x] Hard wrap long lines (skip to avoid interfering with edits in progress)

Supersedes #280

### CODE REVIEW

**Comment by jdinan** [comment]
@gmegan @nspark Please review b3b20d4

**Comment by nspark** [comment]
@jdinan b3b20d4 looks good to me!

**Comment by gmegan** [comment]
@jdinan Thanks Jim. The document looks good. The only green I am finding in the pdf is in the signals section.

**Comment by jdinan** [comment]
@gmegan Thanks!  I fixed the green markings from put-with-signal in #300.  I just merged those changes into this branch from master, so that should be fixed now.

**Pull request merged**
