### PR TITLE
Add Makefile for examples

### PR DESCRIPTION
**Pull request by jdinan**
This PR only adds the makefile for automating building and running the examples.  It's not perfect, but it should be a reasonable start for us to build on.

Note: the Fortran tests are not even compiling right now, so they are omitted from the ```run``` target.

Needs two reviews to merge: @dkhaldi @shamisp or others, please help

### CODE REVIEW

**Comment by jeffhammond** [comment]
I recommend that you remove "-Wall" since that is not a universal flag.  It is not valid for Intel Fortran (`-warn all`) and IBM XL has not direct equivalent (`-qinfo=all` is close).

**Comment by jeffhammond** [comment]
I will 👍  this once you add my previous comment 😉

**Comment by dkhaldi** [comment]
+1

**Comment by shamisp** [comment]
@jeffhammond I don't think we have to be very concerned with C flags portability issues. 

Having ```-Wall``` is useful for the continues integration build . I think we should keep it. I'm not sure why we need ```-O3```, but I suggest to add ```-Werror```.

**Comment by jdinan** [comment]
I could change this to:
```
CFLAGS ?= -Wall -Werror
FFLAGS ?= -Wall -Werror
```
This allows a usage like ```$ make FFLAGS="-warn all"```.  The eventual goal is to build these tests in CI, so I tend to agree with Pasha that I'd prefer for the defaults to support that model.

**Comment by jeffhammond** [comment]
@shamisp Having the default work as often as possible is nice.  You never know when someone is going to download the examples and expect them to work out of the box.  CI systems are by definition automation and can trivially add whatever diagnostic flags are desired.

**Comment by shamisp** [comment]
@jeffhammond it would be nice to have support for every possible platform, but this means that we would have to put in place some build system for example codes (and not just make.) Do we really want to deal here with autotools/cmake/etc ...

**Comment by jdinan** [comment]
@shamisp I think Jeff's suggestion is that we can trivially support any platform by just removing the offending compiler options and having users or the CI script specify them on the command line.

**Comment by shamisp** [comment]
The problem is that by default contributors will not do much. This will
lead to poor patches and  going back and forth to fix those.  Since
"examples" is a not real SW projects, IMHO it is fine to make some
assumptions

**Comment by jdinan** [comment]
Jeff says and he's ok with the approach proposed above.  I pushed a new commit with this change.  @shamisp and @dkhaldi, are we ready to merge?

**Comment by shamisp** [comment]
👍

**Pull request merged**
