### PR TITLE
Add deprecation markers to cache API

### PR DESCRIPTION
**Pull request by jdinan**
Add deprecation begin/end markers around cache API description.

### CODE REVIEW

**Comment by jdinan** [comment]
[PDF of proposed changes](https://github.com/openshmem-org/specification/files/886573/main_spec.pdf)

**Comment by jdinan** [comment]
@nspark Please review.

**Comment by nspark** [comment]
@jdinan I would prefer use to use the `DeprecateBlock` environment:
```latex
\begin{DeprecateBlock}
...
\end{DeprecateBlock}
```
If this doesn't work due to LaTeX sensitivities, then I think what you have is fine.

The only other comment, which is mostly stylistic, is that for PR #48 (Fortran deprecation), I only wrapped the API listing in the synopsis section with the deprecation markings. If we prefer consistency, I'd probably favor the style of #48 because it's much easier in LaTeX form, but I see the benefit of marking the whole of the entry.

**Comment by jdinan** [comment]
Sure, here's the updated PDF: [main_spec.pdf](https://github.com/openshmem-org/specification/files/886709/main_spec.pdf)

I think this should merge relatively easily with your Fortran ticket.  We'll just need to remove the extra DeprecateBlock environment.

**Comment by nspark** [comment]
:+1: Looks good. Thanks, Jim!

**Comment by jdinan** [comment]
We need another +1 to merge this change.  @manjugv @shamisp Can you help?

**Comment by shamisp** [comment]
👍

**Pull request merged**
