### PR TITLE
Add shmem_team_ptr

### LINKED ISSUE #319: Add shmem_team_ptr
## Issue

The `shmem_ptr` operation takes a PE argument that is always relative to `SHMEM_TEAM_WORLD`.

## Proposed Solution

Add team-based variant of `shmem_ptr` as suggested by @naveen-rn on #307. This function's PE argument is relative to the team argument:

`void * shmem_team_ptr(shmem_team_t team, void *ptr, int pe)`

### PR DESCRIPTION
**Pull request by agrippa**
Resolving issue #319 , adding a team-based variant to shmem_ptr.

@jdinan @naveen-rn please let me know if you have any suggestions for different semantics.

Closes #319

### CODE REVIEW

**Comment by kholland-intel** [comment]
Hey @agrippa, do you mind if I spin this patch into a new PR so that I can add a changelog entry and also update the `shmem_ptr` summary to mention that that routine is relative to the world team?

**Comment by kholland-intel** [comment]
Also, @jdinan should the changelog entry go under a new "Version 1.6" subsection?

**Comment by agrippa** [comment]
@kholland-intel no objections on my side, please feel free to close and replace this PR.

**Comment by jdinan** [comment]
@kholland-intel Yes, this is the first change for Version 1.6. Could you please add the new version heading to the changelog?

**Comment by kholland-intel** [comment]
Hey @jdinan and @agrippa, I have opened PR #475 which pulls in the changes from this PR and adds in the changelog updates, etc.

**Pull request merged**
